name: vsss
description: A prototype for a virtual student support service mobile app
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bloc: ^8.1.2
  hydrated_bloc: ^9.1.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  shimmer: ^3.0.0
  path_provider: ^2.1.1
  dartz: ^0.10.1
  get_it: ^7.6.2
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/
